### ISSUE TITLE
Please add examples for all the possible resources for the backup tool

### ISSUE THREAD

**Issue by MDBeudekerCN** [solidify/azure-devops-backup-tool-docs#1]
On this page, some simple examples for AZDO export pipelines are documented:
https://marketplace.visualstudio.com/items?itemName=solidify.ado-backup-tool&ssr=false

Example:
```
# Run export job
- task: ado-backup-tool-export@1
  displayName: 'ADO Backup Tool: Export'
  inputs:
    source: 'https://dev.azure.com/solidifydemo'
    sourceOrgName: 'solidifydemo'
    sourceProject: 'ContosoAir'
    sourceUsername: 'john.doe@solidify.dev'
    sourcePAT: '$(migrationToken)'
    onPrem: false
    workspace: 'C:\AdoBackupWorkspace'
    resourceWorkItem: true
  env:
    SYSTEM_ACCESSTOKEN: $(system.accesstoken)

# Save a snapshot on the backup server (here denoted with X:\)
- task: ArchiveFiles@2
  inputs: 
    rootFolderOrFile: 'C:\AdoBackupWorkspace'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: 'X:\AdoBackupFolder\Backup-$(Build.BuildNumber).zip'
    replaceExistingArchive: false
```

This is the example of a export job that exports WorkItems.

Please add a list of all the other possible items in the list below I see which resources are possible but I would also like the correct syntax in order to import this in my AZDO config; 

```
The following resources are supported as of today:
    Area/Iteration paths
    Teams and team settings
        Team board configuration
    Git repositories
        Pull requests
        Branch policies
    Project wikis
```
